# Nacos同Consul一样，在项目初始化时，要保证先从配置中心进行配置拉取，拉取配置之后，才能保证项目的正常启动，为了满足动态刷新和全局广播通知springboot中配置文件的加载是存在优先级顺序的，bootstrap优先级高于application
server:
  port: 3377

spring:
  profiles:
#     active: dev # 表示开发环境
    active: prod # 表示生产环境
#    active: test # 表示测试环境