# applicaiton.yml是用户级的资源配置项
server:
  port: 8001

# ==========applicationName + druid-mysql8 driver===================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_24?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  profiles:
    active: dev # 多环境配置加载内容dev/prod,不写就是默认default配置

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xi.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

# ========================zipkin分布式链路跟踪系统图形化工具===================
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率百分比 采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。



# ################################### 使用bootstrop前的配置 ###############################################################
#server:
#  port: 8001
#
## ==========applicationName + druid-mysql8 driver===================
#spring:
#  application:
#    name: cloud-payment-service
#
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud_24?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#  ####Spring Cloud Consul for Service Discovery(服务发现)
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        # 8001将要以这个名字入驻进Consul
#        service-name: ${spring.application.name}
#
## ========================mybatis===================
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.xi.cloud.entities
#  configuration:
#    map-underscore-to-camel-case: true
# ################################# 使用bootstrop前的配置结束 #############################################################

