server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider # 入驻进nacos后的微服务名字
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置Nacos地址
    # 优化 OpenFeign和Sentinel集成实现fallback服务降级, 该服务需要被sentinel监控
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
